name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy cppcheck
          
      - name: Check code formatting
        run: |
          find . -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file -i
          git diff --exit-code
          
      - name: Run static analysis
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          cd ..
          find . -name "*.cpp" | xargs clang-tidy -p build
          
      - name: Run cppcheck
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 .

  build-linux:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qt5-default
          
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          
      - name: Build
        run: |
          cd build
          cmake --build .
          
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
